language: rust
os:
  - windows
rust:
  - nightly
scripts:
  - cargo build --release
deploy:
  provider: releases
  api_key:
    secure: "$GITHUB_TOKEN"
  file: "target/release/ssh-cmd-export.exe"
  skip_cleanup: true
  on:
    tags: true
