[package]
name = "ssh-cmd-export"
version = "0.1.0"
authors = ["zhuangqiubin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2 = "0.8"
clap = "2.33.3"
chrono = "0.4"